export struct AlbumItem {
    title: string,
    artist: string,
    album: string,
    album-art: image,
    id: int,
}

export global MainBrowsingState {
    // the list of albums/tracks in the folder
    in property <[[AlbumItem]]> tracks;
    in property <int> max-per-row;
    callback album-view-width-changed();
    callback begin-reload-all-tracks();
}

export global PlayerTabState {
    // likely that volume/share thingy
}

export global PlayingState {
    in property <image> album-art;
    in property <bool> is-playing: false;
    callback enter(int);
    callback play();
    callback pause();
    callback next();
}
