import { PlayingState, MainBrowsingState, AlbumItem } from "global.slint";
import {
    MaterialWindow,
    SmallAppBar,
    NavigationBar,
    ModalNavigationDrawer,
} from "material/material.slint";
import { Palette } from "std-widgets.slint";

global NavBind {
    in-out property <int> nav-group;
    in-out property <int> nav-index;
}

export component MainWindow inherits MaterialWindow {
    default-font-family: "DejaVu Sans";
    preferred-height: 640px;
    preferred-width: 480px;
    title: "Mioplays";
    background: Palette.background;

    VerticalLayout {
        appbar := SmallAppBar {
            title: "Mioplays";
        }

        nav-drawer := ModalNavigationDrawer {
            current-group <=> NavBind.nav-group;
            current-index <=> NavBind.nav-index;
            width: root.width;
            height: root.height;
        }
    }
}

export { MainBrowsingState, PlayingState, AlbumItem }
