import { PlayingState, MainBrowsingState, AlbumItem } from "global.slint";
import {
    MaterialWindow,
    SmallAppBar,
    NavigationBar,
    ModalNavigationDrawer,
    Vertical,
    ScrollView,
    Grid,
    FilledCard,
    Horizontal,
} from "material/material.slint";
import { Palette, AboutSlint } from "std-widgets.slint";

global NavBind {
    in-out property <int> nav-group;
    in-out property <int> nav-index;
}

component AlbumView inherits ScrollView {
    private property <length> card-size: 192px;
    changed width => {
        // on width update, also update the internal representation
        MainBrowsingState.max-per-row = self.width / card-size;
        MainBrowsingState.album-view-width-changed()
    }

    Vertical {
        for row[i] in MainBrowsingState.tracks: Horizontal {
            for album[j] in row: FilledCard {
                // square, with text afterward
                width: card-size;
                max-height: self.width + 36px;

                // playing interaction
                clickable: true;
                clicked => {
                    // TODO: add playing interaction
                }

                // album into
                Vertical {
                    alignment: start;

                    Image {
                        source: album.album-art;
                        width: 100%;
                    }

                    Horizontal {
                        alignment: start;
                        padding: 0px;

                        Text {
                            text: album.title;
                        }
                    }

                    Horizontal {
                        alignment: start;
                        padding: 0px;

                        Text {
                            text: album.artist;
                            font-size: 8px;
                        }
                    }

                    Horizontal {
                        alignment: start;
                        padding: 0px;

                        Text {
                            text: album.album;
                            font-size: 8px;
                        }
                    }
                }
            }
        }
    }
}

export component MainWindow inherits MaterialWindow {
    default-font-family: "DejaVu Sans";
    preferred-height: 640px;
    preferred-width: 480px;
    title: "Mioplays";
    background: Palette.background;
    Vertical {
        appbar := SmallAppBar {
            title: "Mioplays";
            leading-button: { tooltip:"Menu", enabled:true };
            leading-button-clicked => {
                nav-drawer.show()
            }
        }

        AlbumView { }

        nav-drawer := ModalNavigationDrawer {
            current-group <=> NavBind.nav-group;
            current-index <=> NavBind.nav-index;
            width: root.width;
            height: root.height;
            x: 0;
            y: 0;

            groups: [{ title: "Main", items: [{ text: "Albums" }, { text:"Search" }] }];
        }
    }
}

export { MainBrowsingState, PlayingState, AlbumItem }
