import { PlayingState, MainBrowsingState, AlbumItem } from "global.slint";
import {
    MaterialWindow,
    SmallAppBar,
    NavigationBar,
    ModalNavigationDrawer,
    Vertical,
} from "material/material.slint";
import { Palette } from "std-widgets.slint";

global NavBind {
    in-out property <int> nav-group;
    in-out property <int> nav-index;
}

export component MainWindow inherits MaterialWindow {
    default-font-family: "DejaVu Sans";
    preferred-height: 640px;
    preferred-width: 480px;
    title: "Mioplays";
    background: Palette.background;
    Vertical {
        appbar := SmallAppBar {
            title: "Mioplays";
            leading-button: { icon:@image-url("../../img.jpg"), tooltip:"Menu", enabled:true };
            leading-button-clicked => {
                nav-drawer.show()
            }
        }

        nav-drawer := ModalNavigationDrawer {
            current-group <=> NavBind.nav-group;
            current-index <=> NavBind.nav-index;
            width: root.width;
            height: root.height;
            x: 0;
            y: 0;

            groups: [{ title: "Main", items: [{ text: "Albums" }, { text:"Search" }] }];
        }
    }
}

export { MainBrowsingState, PlayingState, AlbumItem }
